BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "vote" (
	"DID"	INTEGER,
	"NID"	TEXT,
	"Stance"	INTEGER NOT NULL CHECK("Stance" IN (0,1,2)),
	PRIMARY KEY("DID","NID"),
	FOREIGN KEY("DID") REFERENCES "debate"("DID"),
	FOREIGN KEY("NID") REFERENCES "nation"("NID")
);
CREATE TABLE IF NOT EXISTS "proposal_author" (
	"PID"	TEXT,
	"Author"	TEXT,
	"Submitting"	INTEGER NOT NULL CHECK("Main" IN (0,1)),
	PRIMARY KEY("PID","Author"),
	FOREIGN KEY("PID") REFERENCES "debate"("PID")
);
CREATE TABLE IF NOT EXISTS "debate" (
	"DID"	INTEGER,
	"PID"	TEXT NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL,
	"Forum"	INTEGER,
	"Discord"	INTEGER UNIQUE,
	"RMB"	INTEGER UNIQUE,
	PRIMARY KEY("DID")
);
CREATE TABLE IF NOT EXISTS "opinion" (
	"DID"	INTEGER,
	"NID"	TEXT,
	"Opinion"	TEXT NOT NULL,
	PRIMARY KEY("DID","NID"),
	FOREIGN KEY("DID") REFERENCES "debate"("DID"),
	FOREIGN KEY("NID") REFERENCES "nation"("NID")
);
CREATE TABLE IF NOT EXISTS "reco" (
	"DID"	INTEGER,
	"Stance"	INTEGER CHECK("Stance" IN (0,1,2)),
	"Analysis"	TEXT,
	"Override"	INTEGER NOT NULL CHECK("Override" IN (0,1)),
	PRIMARY KEY("DID","Stance"),
	FOREIGN KEY("DID") REFERENCES "debate"("DID")
);
CREATE TABLE IF NOT EXISTS "nation" (
	"NID"	TEXT,
	"User"	INTEGER,
	PRIMARY KEY("NID")
);
COMMIT;
