BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "vote" (
	"DID"	TEXT,
	"NID"	TEXT,
	"Stance"	INTEGER NOT NULL,
	PRIMARY KEY("DID","NID")
);
CREATE TABLE IF NOT EXISTS "opinion" (
	"DID"	TEXT,
	"NID"	TEXT,
	"Opinion"	TEXT,
	PRIMARY KEY("DID","NID"),
	FOREIGN KEY("NID") REFERENCES "nation"("NID"),
	FOREIGN KEY("DID") REFERENCES "debate"("DID")
);
CREATE TABLE IF NOT EXISTS "reco" (
	"DID"	INTEGER NOT NULL,
	"Stance"	INTEGER NOT NULL,
	"Analysis"	TEXT,
	"Override"	INTEGER NOT NULL,
	PRIMARY KEY("DID","Stance"),
	FOREIGN KEY("DID") REFERENCES "debate"("DID")
);
CREATE TABLE IF NOT EXISTS "debate" (
	"DID"	TEXT,
	"Title"	TEXT NOT NULL,
	"Forum"	INTEGER,
	"Discord"	INTEGER NOT NULL UNIQUE,
	"RMB"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("DID")
);
CREATE TABLE IF NOT EXISTS "nation" (
	"NID"	TEXT,
	"User"	INTEGER,
	PRIMARY KEY("NID")
);
COMMIT;
